#!/bin/sh

rm -rf build

mkdir -p build

cd build

cmake -DDEVELOPER_MODE=ON -DFIRMWARE_UPDATE=OFF -DFACTORY_MODE=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS="$(TARGET_CFLAGS) -std=gnu99 -pthread -DMBED_CONF_APP_DEVELOPER_MODE=1 -DPAL_DTLS_PEER_MIN_TIMEOUT=5000 -DPAL_SUPPORT_IP_V6=false -DPAL_NET_DNS_IP_SUPPORT=2 -DPAL_USE_SSL_SESSION_RESUM=0" ..
make

ls -al bin
